#!/usr/bin/env python
from __future__ import print_function
import sys
from subprocess import Popen

try:
    import dbus
except ImportError:
    print("dbus-python from http://www.freedesktop.org/wiki/Software/"+ 
          "DBusBindings#python needed")
    sys.exit(1)

started=False
cmd=["/usr/bin/env", "exaile",]
    
session_bus = dbus.SessionBus()
while 1:
    if not 'org.exaile.Exaile' in session_bus.list_names():
        if not started:
            exaile = Popen(cmd)
    else:
        break
remote_object = session_bus.get_object("org.exaile.Exaile","/org/exaile/Exaile")
iface = dbus.Interface(remote_object, "org.exaile.Exaile")
while 1:
    try:
        iface.TestService("TEST")
    except dbus.exceptions.DBusException, e:
        pass
    else:
        break
cmd.extend(sys.argv[1:])
Popen(cmd)
sys.exit(0)
